[package]
name = "libconcentratord"
version = "3.0.0"
authors = ["Orne Brocaar <@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
zmq = "0.9"
lazy_static = "1.4"
chirpstack_api = { version = "3.11.1", default-features = false }
uuid = { version = "0.8", features = ["v4"] }
prost = "0.8"
prost-types = "0.8"
gpio-cdev = "0.4"

[features]
default = ['zmq/vendored']
